### ISSUE TITLE
Feature Request: Expose camera clipping distances and viewing angles.

### ISSUE THREAD

**Issue by sgparry** [TheAliceProject/alice3#278]
The clipping distances in Alice are fixed and very limited for any projects involving interacting with a large scene.
Early versions of Alice exposed the camera parameters in such a way they could be adjusted to suit larger projects. This FR is for that functionality to be added to Alice 3.x. Pull request to follow.

**Comment by dabeshouse** [comment]
The PR looks great, thank you!
All the translations, very nice.

There are a few complicating factors.
The biggest is what happens if a world using it is exported and run in the player. I want to sort that out before merging this in.
Another consideration is how to clear either of the angles. Internally a value of NaN is clear, so a user could restore the default with `setHorizontalViewingAngle: 0.0/0.0`. We are debating if we want to teach this or offer a cleaner mechanism. 
A smaller consideration is the exposing of angles to the user. You are consistent with turn/roll and chose rotations as your units. Switching to degrees or radians might make more sense when thinking about camera views, but I do appreciate  the consistency.

I will sort through the first, hem and haw about the other two, and then I hope to merge this in. Thank you so much for contributing.

**Comment by dabeshouse** [comment]
Yes worlds that use this break in the player. I have changes to address that and will get them in.
I have merged in your PR. Thank you for it.
